# Dataset Related
num_points: 4096  # number of poins actually used in training and evaluation
dataset:
  common:
    NAME: ObjAugDataSet 
    # data_dir: '/mnt/data_sdb/obj/'
    pc_root: '/mnt/data_sdb/obj/'
    # ann_path: '/home/hhfan/code/point-transformer/process/label/test_selected_4_uid_path_idx_dict.json'
  train:
    split: train
    num_points: 4096  # in training, use sampled 1024 points for data augmentation. 
  val:
    split: test
    num_points: 4096  # in testing, use uniformly pre-sampled 1024 points for evaluation (following https://github.com/lulutang0608/Point-BERT) 

feature_keys: pos

datatransforms:
  train: [PointsToTensor, PointCloudScaleAndTranslate]  # rotation does not help
  vote: [PointCloudScaleAndTranslate]
  val: [PointsToTensor]
  kwargs:
    shift: [0.2, 0.2, 0.2]
batch_size: 32
dataloader:
  num_workers: 16

num_classes: 908
# ---------------------------------------------------------------------------- #
# Training cfgs
# ---------------------------------------------------------------------------- #
# training receipe borrowed from: https://github.com/yanx27/Pointnet_Pointnet2_pytorch

# ---------------------------------------------------------------------------- #
# Training cfgs
# ---------------------------------------------------------------------------- #
# this one is better. 
sched: cosine
epochs: 600
warmup_epochs: 0
min_lr: null 

# Training parameters
lr: 0.001
optimizer:
 NAME: 'adamw'
 weight_decay: 0.05 

grad_norm_clip: 1

criterion_args:
  NAME: SmoothCrossEntropy
  label_smoothing: 0.2

# ---------------------------------------------------------------------------- #
# io and misc
# ---------------------------------------------------------------------------- #
log_dir: 'objaug_px'
print_freq: 20
val_freq: 1

# ----------------- Model related
val_batch_size: 64
pretrained_path: null 

# wandb:
#   project: PointNeXt-ModelNet40Ply2048

seed: null